name: Daily Commit


on:
  schedule:
    - cron: '45 17 * * *'
  workflow_dispatch:      # Allows manual triggering

jobs:
  commit_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file (22f2000788@ds.study.iitm.ac.in)
        run: |
          echo "Updated on $(date)" >> daily-log.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit"
          git push


# will not run anymore
